Fix C++20 Warning
```
src/elements/QuadEdge.H:113:26: error:
  arithmetic between enumeration type
  ‘impactx::elements::QuadEdge::Location’
  and floating-point type ‘amrex::ParticleReal’
  {aka ‘double’} is deprecated
  [-Werror=deprecated-enum-float-conversion]
```