SIMD: Portable Masks, C++20 (#1092)
* SIMD: Portable Masks, C++20

See https://github.com/AMReX-Codes/amrex/pull/4607

* Fix C++20 Warning

```
src/elements/QuadEdge.H:113:26: error:
  arithmetic between enumeration type
  ‘impactx::elements::QuadEdge::Location’
  and floating-point type ‘amrex::ParticleReal’
  {aka ‘double’} is deprecated
  [-Werror=deprecated-enum-float-conversion]
```